apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "enginemq-broker.fullname" . }}
  labels:
    {{- include "enginemq-broker.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "enginemq-broker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "enginemq-broker.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: socket
              containerPort: 16677
              protocol: TCP
            - name: web
              containerPort: 16688
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 16677
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 16677
            initialDelaySeconds: 5
            periodSeconds: 20
          volumeMounts:
            - name: brokerdata
              mountPath: /brokerdata
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: LOG_LEVEL
              value: "{{ .Values.log.logLevel }}"
            - name: WEBUI_ENABLED
              value: "{{ .Values.service.enableWebUI }}"
          {{- if .Values.heartBeatSec }}
            - name: HEARTBEAT_SEC
              value: "{{ .Values.heartBeatSec }}"
          {{- end }}
          {{- if .Values.persistence.enabled }}
            - name: STORAGE
              value: "sqlite3(file=/brokerdata/enginemq-broker.sqlite3)"
          {{- else }}
            - name: STORAGE
              value: "null()"
          {{- end }}
          {{- if .Values.resourceOrigin }}
            - name: RESOURCE_ORIGIN
              value: "github(repo={{ .Values.resourceOrigin.repo }} token={{ .Values.resourceOrigin.token }} branch={{ .Values.resourceOrigin.branch }} folder={{ .Values.resourceOrigin.folder }})"
          {{- end }}
      volumes:
        - name: brokerdata
      {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "enginemq-broker.fullname" . }}
      {{- else }}
          emptyDir: {}
      {{- end -}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
